### ISSUE TITLE
PDF Header Not shown

### ISSUE THREAD

**Issue by farhadbarati** [chamilo/docs#14]
when i export exam result in pdf, the pdf header (my logo) not shown and just show only red X. how can i put my LMS logo in pdf header?
thanks.

**Comment by ywarnier** [comment]
Hi @farhadbarati 
Not sure how you got here, but this is not the right place to report this. This (here) is the documentation project for Chamilo, not the Chamilo LMS software project itself.
You want to report this here: https://github.com/chamilo/chamilo-lms/issues instead, making sure you use the templates to report issues so that we can help you better.
