### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by 22phuber** [chamilo/docs#25]
Hy there Chamilo lms team

I've generated German translations from the english source documentation using AWS translate. You can find it here: https://github.com/StoneAge-IT/docs/tree/1.11.x-de

It's not perfect as of now, but already pretty neat and a good start.

I created a new branch `1.11.x-de` on my forked repository which doesn't yet exist on your `chamilo/docs` repository. I originally branched from the `1.11.x`

If you could create this branch I could make a Pull Request against it (if you want me to)? Is this something you are interested in?

regards, 
Patrick

**Comment by ywarnier** [comment]
Nice. I just created the 1.11.x-de branch.
Also nice to see AWS can be used for that, because translating manually is a huuuuge undertaking.

**Comment by 22phuber** [comment]
Hi @ywarnier

Thank you for creating the new branch. 
I've created the [PR](https://github.com/chamilo/docs/pull/26). 

Well, you can use AWS translate, but I needed to write my own "parser" to extract content before translating and insert it back in again afterwards. Also there is a limitation of 5KB of data in a single translation request. But in the end it was a fun thing to do.

**Comment by ywarnier** [comment]
Hi @22phuber Sorry for the long wait. I merged your PR so the guide should appear on https://docs.chamilo.org as 1.11.x-de in a few hours at the most. If you see I'm taking a long time to answer, just insist. I receive about 300 e-mails per day and cannot always attend those (and I'm the one in charge of the documentation project because no-one else has the required combination of skills and experience), so sometimes I might miss an e-mail with an update request like yours.
